ALTER TABLE KITAP 
ADD CONSTRAINT fk_kitap_kategori
FOREIGN KEY (KategoriID)
REFERENCES KATEGORI(KategoriID)
ON DELETE RESTRICT;

ALTER TABLE ODUNC
ADD CONSTRAINT fk_odunc_uye
FOREIGN KEY (UyeID)
REFERENCES UYE(UyeID)
ON DELETE RESTRICT;

ALTER TABLE ODUNC 
ADD CONSTRAINT fk_odunc_gorevli
FOREIGN KEY (GorevliID)
REFERENCES KULLANICI(KullaniciID)
ON DELETE RESTRICT;

ALTER TABLE ODUNC 
ADD CONSTRAINT fk_odunc_kitap
FOREIGN KEY (KitapID)
REFERENCES KITAP(KitapID)
ON DELETE RESTRICT;

ALTER TABLE CEZA
ADD CONSTRAINT fk_ceza_odunc
FOREIGN KEY (OduncID)
REFERENCES ODUNC(OduncID)
ON DELETE CASCADE;